services:
  - type: web
    name: portfolio-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DATABASE_NAME
        value: portfolio_db
      - key: GITHUB_USERNAME
        sync: false
      - key: PORT
        value: 5000
